---
- set_fact:
    go_version: stable
  when: go_version is undefined

- include_tasks: "{{ item }}"
  with_first_found:
    - fetch-package/fetch-package-{{ go_version }}.yml
    - fetch-package/fetch-package-custom.yml
